### ISSUE TITLE
how can I tell if my phone is global or china?

### ISSUE THREAD

**Issue by mmlb** [XiaomiFirmwareUpdaterReleases/firmware_xiaomi_dipper#1]
I already have lineage os running so the `MIUI Name` in the table is seemingly not useful. Is there a way to tell the flavor from lineage-os somehow?

**Comment by yshalsager** [comment]
@mmlb It's depending on where did you get the device from, If it's China, then mostly your device is Chinese.

**Comment by mmlb** [comment]
Yes, I went exploring some more and figured out that unless I know I have the chinese version then I lkely have the global fw. I correlated that info with info on the radio frequencies and the chinese version would not work for me. I think it would be nice to have this a little more visible in this project somewhere.
